spring:
  application:
    name: payment-service

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
      retry:
        max-attempts: 20

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

stripe:
  secret-key: sk_test_51Rl85dJWBx0SUW4z7dLmPPfFv5DgP2MvwiElnWU9XXlXhHyYVoHJMGt3sjFgNE5MuHzaFVpTntsbFDs8ZoOfLuYz00dtQBHulc
  success-url: http://localhost:8080/success
  cancel-url: http://localhost:8080/cancel
