spring:
  application:
    name: api-gateway

  profiles:
    active: ${ACTIVE_PROFILE:dev}

  config:
    import: "optional:configserver:"

  main:
    web-application-type: reactive

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: false
      profile: dev

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/