spring:
  application:
    name: discovery-server

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

otel:
  metrics:
    exporter: none
  logs:
    exporter: none
  exporter:
    otlp:
      endpoint: http://${TEMPO_HOST:localhost}:${TEMPO_PORT:4318}/
