spring:
  main:
    web-application-type: reactive
  application:
    name: ApiGateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            ## User Service Route
            - id: UserService
              uri: lb://userservice
              predicates:
                - Path=/user/api/**, /profile/api/**, /city/api/**, /address/api/**, /paymentmethod/api/**

            ## Order Service Route
            - id: OrderService
              uri: lb://orderservice
              predicates:
                - Path=/order/api/**

            ## Inventory Service Route
            - id: InventoryService
              uri: lb://inventoryservice
              predicates:
                - Path=/inventory/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

otel:
  metrics:
    exporter: none
  logs:
    exporter: none

server:
  port: 4000