spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ilyass-Bougati/alexandre-config.git
          skip-ssl-validation: true
          clone-on-start: true

          # Refreshing the config each 30 seconds
          refresh-rate: 30

      override-none: true

otel:
  metrics:
    exporter: none
  logs:
    exporter: none
  traces:
    exporter: none

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka/

server:
  port: 8888
